// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndvgdwvipyipjztdlbmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kdmdkd3ZpcHlpcGp6dGRsYm1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTU2ODIsImV4cCI6MjA2NTM3MTY4Mn0.F32h2NKkR4Ny49JRz9Xo43cnsCccyJkZzxWQKULK3fY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);